// Database Type Definitions
// NOTE: The Database type below is a placeholder and will be auto-generated by Supabase CLI
// To generate types from your database schema, run:
// supabase gen types typescript --linked > src/lib/database.types.ts
//
// Until then, we use manual helper types below for development

// Placeholder Database type (will be replaced by auto-generated types)
export type Database = {
  // This will be auto-generated by Supabase CLI
  // Run: supabase gen types typescript --linked > src/lib/database.types.ts
};

// ============================================================================
// Manual Helper Types (replace these once auto-generated types are available)
// ============================================================================

export type Profile = {
  id: string;
  email: string;
  full_name: string | null;
  avatar_url: string | null;
  is_verified: boolean;
  external_system_id: string | null;
  created_at: string;
  updated_at: string;
};

export type Session = {
  id: string;
  title: string;
  description: string | null;
  instructor_id: string;
  video_url: string;
  thumbnail_url: string | null;
  scheduled_start: string;
  scheduled_end: string;
  actual_start: string | null;
  actual_end: string | null;
  is_live: boolean;
  chat_enabled: boolean;
  max_viewers: number | null;
  recording_url: string | null;
  created_at: string;
  updated_at: string;
};

export type Message = {
  id: number;
  session_id: string;
  user_id: string;
  user_name: string;
  content: string;
  message_type: 'user' | 'admin' | 'system';
  is_pinned: boolean;
  created_at: string;
};

export type ViewerSession = {
  id: string;
  session_id: string;
  user_id: string | null;
  joined_at: string;
  left_at: string | null;
  duration_seconds: number | null;
};

export type Enrollment = {
  id: string;
  user_id: string;
  session_id: string;
  enrolled_at: string;
};

export type Reaction = {
  id: number;
  message_id: number;
  user_id: string;
  emoji: string;
  created_at: string;
};

export type SessionAnalytics = {
  session_id: string;
  total_viewers: number;
  peak_viewers: number;
  total_messages: number;
  avg_watch_duration_seconds: number;
  unique_chatters: number;
  chat_log: any; // JSONB
  computed_at: string;
};
